spring:
  application:
    name: "starfish"
  profiles:
    active: "csv-application-categories-provider, csv-vendors-provider, csv-applications-provider, csv-accounts-provider, csv-users-provider"

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true
  health:
    applicationCategoryContent:
      enabled: true
    applicationContent:
      enabled: true
    accountContent:
      enabled: true
    userContent:
      enabled: true
    deviceContent:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

## Configuring info endpoint
info:
  app:
    name: starfish
    description: This is the starfish application
    version: 0.0.1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.convert.CustomConversions: ERROR
    org.springframework.data.elasticsearch.support.VersionInfo: ERROR
    org.elasticsearch.client: ERROR
    org.apache.http: INFO
    org.ok.milki: INFO
